Config = {}

Config.Locations = {
    ["main"] = {
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },
    ["thermite"] = {
        x = 158.23, 
        y = -224.31, 
        z = 59.68,
        isDone = false,
        isBusy = false,
    },
    ["takeables"] = {
        [1] = {
            x = 157.05, 
            y = -224.97, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [2] = {
            x = 155.67, 
            y = -224.42, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 6},
        },
        [3] = {
            x = 153.94, 
            y = -223.83, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 3},
        },
        [4] = {
            x = 152.05, 
            y = -223.06, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "samsungphone", amount = 6},
        },
        [5] = {
            x = 150.3, 
            y = -222.51, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "samsungphone", amount = 4},
        },
        [6] = {
            x = 148.79, 
            y = -221.99, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 3},
        },
        [7] = {
            x = 155.41, 
            y = -229.52, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 4},
        },
        [8] = {
            x = 153.9, 
            y = -228.93, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 6},
        },
        [9] = {
            x = 152.26, 
            y = -228.36, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 4},
        },
        [10] = {
            x = 150.39, 
            y = -227.79, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [11] = {
            x = 148.64, 
            y = -227.09, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 1},
        },
        [12] = {
            x = 147.13, 
            y = -226.55, 
            z = 54.42,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 2},
        },
    },
     ["safe"] = {
         x = 147.69, 
         y = -234.07, 
         z = 54.42,
         isDone = false,
         isBusy = false,
     }
}

Config.MaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [18] = true,
    [26] = true,
    [52] = true,
    [53] = true,
    [54] = true,
    [55] = true,
    [56] = true,
    [57] = true,
    [58] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [112] = true,
    [113] = true,
    [114] = true,
    [118] = true,
    [125] = true,
    [132] = true,
}

Config.FemaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [19] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [63] = true,
    [64] = true,
    [65] = true,
    [66] = true,
    [67] = true,
    [68] = true,
    [69] = true,
    [70] = true,
    [71] = true,
    [129] = true,
    [130] = true,
    [131] = true,
    [135] = true,
    [142] = true,
    [149] = true,
    [153] = true,
    [157] = true,
    [161] = true,
    [165] = true,
}